/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <setjmp.h>
/* Header for class no_hyper_ffmpegwrapper_FfmpegService */

extern jmp_buf jmp_exit;

#ifndef _Included_no_hyper_ffmpegwrapper_FfmpegService
#define _Included_no_hyper_ffmpegwrapper_FfmpegService
/*
 * Class:     no_hyper_ffmpegwrapper_FfmpegService
 * Method:    __execute
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_no_hyper_ffmpegwrapper_FfmpegService__1_1execute
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     no_hyper_ffmpegwrapper_FfmpegService
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no_hyper_ffmpegwrapper_FfmpegService_cancel
  (JNIEnv *, jobject);

#endif
